<a href="https://colab.research.google.com/github/albert-magarire/Data-Science-and-ML/blob/main/Magarire_Albert_Project1_Math208.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Project 1 - Solving Random Systems

Below is an example of code that can generate a random matrix with specified number of rows and columns with integer values.  

0. Change the name of the file by replacing the LastName and FirstName with your last name and first name.

In [ ]:
import numpy as np

#Define the dimension of your matrix

rows_A, cols_A = 4, 15 #An example: a 4x15 matrix

low_A, high_A = -20, 20 #These numbers are going to be the bounds for our random integers.  The low is -20 and the high is 20.

#Generate a random integer matrix

A = np.random.randint(low_A, high_A, size=(rows_A, cols_A))

print(A)

[[-13  10  10   9   9   0  15  14  19 -14  18   8   2  14  10]
 [  1  17   7 -10   6 -19 -13   9 -10   9   1  14 -16  15 -13]
 [ -4 -11  -4 -19  14  14 -20  19 -18   9 -10 -20 -10 -18 -20]
 [ -4  12  10   2  11  -4  19  -7 -12 -16 -14  -1   3   2  -1]]


##Part 1

Follow the instructions while reading the project.  Our goal is randomly generate matrices $A$ and $b$ that have a single solution $x$ for the equation $$Ax=b.$$

1. Generate a new random matrix with 5 rows and 10 columns with integer values between -10 and 100.  Call this matrix $A$.

In [ ]:
#Run this cell with appropriate changes

rows_A, cols_A = 5, 10 #An example: a 5x10 matrix

low_A, high_A = -10, 100 #These numbers are going to be the bounds for our random integers.  The low is -10 and the high is 100.

#Generate a random integer matrix

A = np.random.randint(low_A, high_A, size=(rows_A, cols_A))

print(A)


[[60 48 79 43 93 82  7 45  6 49]
 [-6 58 -7 84 18 19 11 23 90 38]
 [22  5 74 17 84 -4 12  1 -1 -7]
 [24  8 27 77 16 73 72 43 54 22]
 [21 13 44  6 21 78 36 -9 29 59]]


2. For this matrix $A$, generate a random column vector, $b$ with integer values between -20 and 15.  The matrix $A$ will help you determine the number of rows for $b$. There should only be 1 column.  

In [ ]:
#Run this cell

rows_b, cols_b = 5,1
low_b,high_b = -20,15

b= np.random.randint(low_b, high_b,size=(rows_b,cols_b))

print(b)

[[-12]
 [  6]
 [-20]
 [  2]
 [ 11]]


3. Solve the system using the x = np.linalg.solve(A,b) command.

In [ ]:
#Run this cell

x = np.linalg.solve(A,b)

LinAlgError: Last 2 dimensions of the array must be square

We get an error! That's absurd. Okay, not really.  We get this error because numpy.linalg.solve uses a method of solving that requires a square matrix.  We have a way around this, multiply both sides of the equation \begin{align*}
Ax &= b
\end{align*} by $A^T$ on the **left**.  Note that if $A$ is a $m\times n$ matrix, then $A^T$ is a $n\times m$ matrix.  Hence, $A^TA$ will be a $n\times n$ matrix. This gives us the equation \begin{align*} (A^TA)x = A^Tb. \end{align*} Now we can use numpy.linalg.solve.

I believe that numpy.linalg.solve requires the use of a square matrix because it wants to multiply both sides by the *inverse* of $A$.  To get $$x=A^{-1}b.$$

When we use numpy.linalg.solve to solve our **new** matrix equation, we are actually finding $$x = (A^TA)^{-1}(A^Tb).$$  In a perfect world, one where $A$ is a square and invertible matrix, $(A^TA)^{-1} = A^{-1}(A^T)^{-1}$.  So our solution would be $$x = A^{-1}b,$$ but our $A$ is not square.  Thus, it is not invertible.  So we actually have that $(A^TA)^{-1} \ne A^{-1}(A^T)^{-1}$ since $A^{-1}$ does not exist.

4. Find $A^T$, label it A_T, and use numpy.linalg.solve to find $x$ that satisfies the equation $$A^TAx=A^Tb.$$

In [ ]:
#First we define the transpose

A_T = np.transpose(A)

#Next we solve the (A_T@A)x = (A_T)b

x = np.linalg.solve(A_T@A,A_T@b)

print(x)

[[ 0.32255769]
 [-0.60242398]
 [ 0.3684132 ]
 [ 0.10971929]
 [-0.5367654 ]
 [-0.24668249]
 [-0.42220599]
 [ 0.17060811]
 [ 0.33614865]
 [ 0.55405405]]


5. If you get that there is no solution since the matrix is singular, this means that $$A^TA$$ is not invertible.  Regenerate $A$ and your code until you get one solution. Go back to the first item and rerun the cells.

6. We can check to make sure that the $x$ we found also satisfies the equation $$Ax=b$$ for our randomly generated matrices by using the numpy.allclose function and defining a tolerance level.

In [ ]:
#Run this cell

#Define a tolerance level

tolerance = 1e-5 #tolerance is 0.00001

are_equal = np.allclose(A@x,b, atol = tolerance) #atol means absolute tolerance

print(are_equal)

True


##Part 2

Do the same thing as before.  This time call the matrix $D$ should be a matrix with 15 rows and 250 columns.  The lower limit of the entries of $D$ should be -50 and the upper limit can be any number you like greater than 25. We want to solve $$Dy=c$$ where $c$ is an appropriate sized column vector with integer values between -100 and 45.  Keep generating until you get a solution for $y$.

In [ ]:
#Input your code here.
# Generate a 15x250 matrix (rows > columns)
rows_D, cols_D = 15, 250
low_D, high_D = -50, 30
D = np.random.randint(low_D, high_D, size=(rows_D, cols_D))

print(D)

[[ -6 -40  13 ... -20  11 -44]
 [-14  10 -24 ...  24   1 -37]
 [ 23  -1 -16 ... -47  26 -41]
 ...
 [  8 -21 -19 ...   5   7 -19]
 [-22 -32  27 ... -47  17  -8]
 [ -1  28  14 ...   8 -18   6]]


In [ ]:
rows_c, cols_c = 15,1
low_c,high_c = -100,45

c = np.random.randint(low_c, high_c,size=(rows_c,cols_c))

print(c)

[[-91]
 [-60]
 [ 21]
 [-73]
 [ 20]
 [-73]
 [-14]
 [ 25]
 [-24]
 [ 41]
 [-70]
 [ -5]
 [ 29]
 [-86]
 [-54]]


In [ ]:
y = np.linalg.solve(D,c)

LinAlgError: Last 2 dimensions of the array must be square

In [ ]:
D_T = np.transpose(D)
y = np.linalg.solve(D_T@D,D_T@c)
print(y)

[[ 2.03287629e+00]
 [-9.33168201e-01]
 [-1.03229655e+01]
 [-6.70021373e-01]
 [-3.23007156e+00]
 [-5.22892384e-01]
 [-7.48444724e-01]
 [ 7.18460069e-01]
 [-6.66109708e-01]
 [ 3.08053861e+00]
 [-5.64299960e-01]
 [ 4.70734554e+00]
 [-6.56433575e+00]
 [-2.38217812e+00]
 [ 5.86141994e+00]
 [ 1.24561155e+00]
 [ 2.13635455e+00]
 [ 1.33253129e+00]
 [-1.50734604e+00]
 [-1.22148902e+00]
 [ 4.49841968e-01]
 [ 7.78417772e-01]
 [-3.56605382e+00]
 [-1.01414185e+00]
 [ 1.27472574e+00]
 [-8.31563385e-04]
 [-1.55895847e+00]
 [ 6.07018986e-01]
 [ 8.13368412e-01]
 [ 2.61359828e+00]
 [-3.36648837e+00]
 [ 1.53763850e+00]
 [-3.18907836e+00]
 [-5.32634364e+00]
 [ 1.13439354e+00]
 [ 3.45064303e-01]
 [-2.51090424e-01]
 [ 2.16007480e-01]
 [ 3.16313530e+00]
 [ 1.33337750e+00]
 [-1.13650219e+00]
 [ 2.76560756e-01]
 [ 1.81749890e+00]
 [-7.70781219e-01]
 [-7.71757292e-01]
 [-1.07372966e+00]
 [ 1.34322857e+00]
 [ 9.58643704e-01]
 [ 1.22654861e+00]
 [-8.51544557e-02]
 [ 1.40806462e-02]
 [ 3.70377824e+00]
 [ 1.7193956

In [ ]:
tolerance = 1e-5 #tolerance is 0.00001

are_equal = np.allclose(D@y,c, atol = tolerance) #atol means absolute tolerance

print(are_equal)

True
